import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import React from "react";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import {Layout} from "antd";
import {Content} from "antd/es/layout/layout";
import Nav from "@/app/component/Nav";
import Slider from "@/app/component/Slider";
import { ConfigProvider } from 'antd';
import {brandColor} from "@/config/theme";

const inter = Inter({
    subsets: ["latin"], display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<html lang="en">
    <body
        className={inter.className}
    >
    <AntdRegistry>
        <Layout hasSider>
            <Slider/>
            <Layout style={{
                background: brandColor.token.colorBgBase,
            }} >
                <Nav/>
                <Content style={
                    {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        justifyContent: 'start',
                        marginTop: '34px',
                        backgroundColor: brandColor.token.colorBgBase,}
                }>
                    <ConfigProvider theme={brandColor}>
                        {children }
                    </ConfigProvider>
                </Content>
            </Layout>
        </Layout>
    </AntdRegistry>
    </body>
    </html>);
}